// Fill out your copyright notice in the Description page of Project Settings.

#include "MyActor02.h" // .cpp æ–‡ä»¶æ–°å¢å¼•å…¥éƒ½æ˜¯å‘åæ–°å¢
#include "Components/StaticMeshComponent.h" // å› ä¸ºä¸‹é¢å®šä¹‰çš„ StaticMesh æ˜¯ä¸€ä¸ªæŒ‡é’ˆç±»å‹, æ‰€ä»¥è¿™é‡Œè¦å¼•å…¥ç»„ä»¶çš„å¤´æ–‡ä»¶ï¼ï¼


// ğŸ‘‡ ç”¨æ¥è®¾ç½® Actor çš„é»˜è®¤å€¼(åˆå§‹å€¼), AMyActor02 ä¸º AMyActor02 çš„æ„é€ å‡½æ•°, åœ¨ç±»å®ä¾‹åŒ–åè‡ªåŠ¨è°ƒç”¨ï¼
AMyActor02::AMyActor02() {
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

    // ğŸ”¥ã€ğŸ‘‡ç»„ä»¶çš„ç”Ÿæˆ: ç›¸å½“äºç”¨ C++ å†™ä¸€ä¸ªé™æ€ç½‘æ ¼ã€‘å¯¹StaticMesh èµ‹äºˆåˆå§‹å€¼, ç”Ÿæˆå®ä¾‹åŒ–çš„ç»„ä»¶
    MyStaticMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MyStaticMesh"));// ç»„ä»¶æ˜¯ Actor çš„å­ç‰©ä½“, ã€ğŸ”¥createDefaultSubobject è¡¨ç¤ºç”Ÿæˆä¸€ä¸ªé»˜è®¤çš„å­ç‰©ä½“ã€‘, ã€ ğŸ”¥UStaticMeshComponent è¡¨ä½¿ç”¨æ¨¡æ¿ç»„ä»¶ ã€‘, ã€ ğŸ”¥TEXT("MyStaticMesh") ä¸æ˜¯åå­—!! è€Œæ˜¯ä¸€ä¸ªæ ‡è¯†ç¬¦å·, å› ä¸º StaticMesh æ˜¯ä¸€ä¸ªæŒ‡é’ˆï¼ã€‘

    // ğŸ‘‡ç»„ä»¶å†…å‚æ•°çš„åˆå§‹åŒ–
    InitLocation = FVector(0.0f); //ğŸ”¥ğŸ”¥ è®¾ç½® Actor ç»„ä»¶çš„ InitLocation å‚æ•°çš„é»˜è®¤å€¼ï¼ˆä½ç½®ï¼‰ FVector(0.0f)
    PlacedLocation = FVector(0.0f); //ğŸ”¥ğŸ”¥ è®¾ç½® Actor ç»„ä»¶çš„ InitLocation å‚æ•°çš„é»˜è®¤å€¼ï¼ˆä½ç½®ï¼‰ FVector(0.0f)
    bGotoInitLocation = false; // é»˜è®¤ç•™åœ¨åŸåˆä½ç½®
    WorldOrigin = FVector(0.0f); //è®°å½•ä¸–ç•ŒåŸç‚¹çš„ä½ç½®
    TickLocationOffset = FVector(0.0f); //ç”¨æ¥è®°å½•æ¯ä¸€å¸§çš„åç§»é‡
    bShouldMove = false; //æ˜¯å¦ç§»åŠ¨
    initForce = FVector(0.0f); //åˆå§‹é‡åŠ›
    initTorque = FVector(0.0f); //åˆå§‹åŠ›çŸ©
    bAccelChange = false;
}



// ğŸ‘‡æ¸¸æˆç”Ÿæˆæ—¶è°ƒç”¨, Called when the game starts or when spawned
void AMyActor02::BeginPlay() {
	Super::BeginPlay();

    // ğŸš©ğŸš© Actor (BeginPlay å‡ºç”Ÿç‚¹)çš„åˆå§‹åŒ–ä½ç½®, GetActorLocation() ä¸ºå†…ç½®æ–¹æ³•
    PlacedLocation = GetActorLocation(); //ã€è·å–ã€‘ Actor çš„å‡ºç”Ÿç‚¹ä½ç½®, GetActorLocation ä¸ºå†…ç½®æ–¹æ³•


    // æ ¹æ®ã€è“å›¾ç±»çš„è®¾ç½®ã€‘ï¼ˆå¼€å…³å†³å®šæ˜¯å¦å›åˆ°è®¾ç½®çš„åˆå§‹ç‚¹ï¼‰
    if(bGotoInitLocation) { // SetActorLocation() ä¸ºå†…ç½®æ–¹æ³•
        SetActorLocation(InitLocation); //ã€è®¾ç½®ã€‘é»˜è®¤å‡ºç”Ÿç‚¹åœ¨ 0,0,0  //SetActorLocation(FVector(0.0f)); //é»˜è®¤å‡ºç”Ÿç‚¹åœ¨ 0,0,0
    }

    // ğŸš€ğŸš€ MyStaticMesh æ˜¯ä¸€ä¸ªæŒ‡é’ˆï¼, ç®­å¤´è¿ç®—ç¬¦ "->" ç”¨äºè®¿é—®æŒ‡é’ˆæ‰€æŒ‡å‘çš„å¯¹è±¡çš„æˆå‘˜, ä¸‹é¢ä¸¤ä¸ªæ–¹æ³•å‰ææ˜¯è¦åœ¨ç¼–è¾‘å™¨å†…å¯ç”¨æ¨¡æ‹Ÿç‰©ç†ï¼æˆ–è€…åœ¨ğŸ‘‡ä¸‹é¢çš„æ–¹æ³•ä¸­åŠ ä¸Š sweep!!
//    MyStaticMesh -> AddForce(initForce, "NAME_NONE", bAccelChange); //ç»™ ã€Actor03 å®ä¾‹ã€‘æ·»åŠ é‡åŠ›, æ·»åŠ åˆ°ä»€ä¹ˆéª¨éª¼ä¸Š, bAccelChange æ˜¯ç¬¬ä¸‰ä¸ªå‚æ•° -> æ˜¯å¦å¿½ç•¥è´¨é‡ï¼ˆè®©ç‰©ä½“ä¸å—é‡åŠ›å½±å“ï¼‰
//    MyStaticMesh -> AddTorqueInDegrees(initTorque, "NAME_NONE", bAccelChange); //ç»™ ã€Actor03 å®ä¾‹ã€‘æ·»åŠ åŠ›çŸ©, æ·»åŠ åˆ°ä»€ä¹ˆéª¨éª¼ä¸Š, bAccelChange æ˜¯ç¬¬ä¸‰ä¸ªå‚æ•° -> æ˜¯å¦å¿½ç•¥è´¨é‡ï¼ˆè®©ç‰©ä½“ä¸å—é‡åŠ›å½±å“ï¼‰
}




// ğŸ‘‡æ¯å¸§è°ƒç”¨, Called every frame
void AMyActor02::Tick(float DeltaTime) {
	Super::Tick(DeltaTime);

    if(bShouldMove) {
        FHitResult HitResult; //å£°æ˜ä¸€ä¸ªç¢°æ’ç»“æœ(åœ¨å“ªé‡Œäº§ç”Ÿç¢°æ’)
        AddActorLocalOffset(TickLocationOffset, true, &HitResult); // AddActorLocationOffset ä¸ºå†…ç½®æ–¹æ³•, ä¼šæ›´æ”¹ç‰©ä½“çš„ä½ç½®, å€¼æ¥è‡ª TickLocationOffset ğŸ‘ˆè¿™ä¸ªå€¼æ˜¯æˆ‘ä»¬å®šä¹‰çš„, å¯ä»¥åœ¨å®ä¾‹çš„ detail é¢æ¿ä¸­è¿›è¡Œè¾“å…¥ï¼ï¼ï¼ ç¬¬äºŒä¸ªå‚æ•° true è¡¨ç¤ºå¯ç”¨æ‰«æ(sweep)ï¼Œå¯ä»¥åœ¨ä¸å¯ç”¨æ¨¡æ‹Ÿç‰©ç†çš„æƒ…å†µä¸‹è®©ç‰©ä½“è·Ÿç‰©ä½“è·¯å¾„ä¸Šäº§ç”Ÿç¢°æ’ğŸ’¥ï¼
        UE_LOG(LogTemp, Warning, TEXT("X: %f, Y: %f, Z: %f"), HitResult.Location.X, HitResult.Location.Y, HitResult.Location.Z); //%f è¡¨ç¤ºç™¾åˆ†ä¹‹å¤šå°‘çš„æµ®ç‚¹æ•°
    }
}

